### ISSUE TITLE
Not sure why am i getting this error UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

### ISSUE THREAD

**Issue by xSyrix** [jQwotos/Kissanime-Mass-Downloader#2]
Found the directory, navigating into it.
/home/jc/Downloads/Kissanime-Mass-Downloader/Downloads
/home/jc/Downloads/Kissanime-Mass-Downloader/Downloads/Log-Horizon-Dub
Found a previously downloaded episodes
I will be scanning the directory for the episodes now.
Downloaded episodes detected:[]
Traceback (most recent call last):
  File "Alpha.py", line 223, in <module>
    handler = Thread_Handler()
  File "Alpha.py", line 70, in __init__
    self.start()
  File "Alpha.py", line 75, in start
    downloader.start(dld)
  File "Alpha.py", line 85, in start
    self.findEpisodes()
  File "Alpha.py", line 125, in findEpisodes
    self.findPrev()
  File "Alpha.py", line 168, in findPrev
    self.download()
  File "Alpha.py", line 183, in download
    if str(link.text) == quality:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

please advise what should i do ?

**Comment by jQwotos** [comment]
@xSyrix could you post the full command that you used to start the script, thanks

**Comment by xSyrix** [comment]
@jQwotos thx for replying fast.

here is the whole output 


python Alpha.py -l "https://kissanime.to/Anime/Log-Horizon-Dub"
Initializing Scraper, this may take 5 - 10 seconds
Logging in with bot credentials
Logged in
('Starting to Download: ', 'https://kissanime.to/Anime/Log-Horizon-Dub')
/Anime/Log-Horizon-Dub/Episode-025?id=88694
/Anime/Log-Horizon-Dub/Episode-024?id=88693
/Anime/Log-Horizon-Dub/Episode-023?id=88692
/Anime/Log-Horizon-Dub/Episode-022?id=88691
/Anime/Log-Horizon-Dub/Episode-021?id=88690
/Anime/Log-Horizon-Dub/Episode-020?id=88689
/Anime/Log-Horizon-Dub/Episode-019?id=88688
/Anime/Log-Horizon-Dub/Episode-018?id=88687
/Anime/Log-Horizon-Dub/Episode-017?id=88686
/Anime/Log-Horizon-Dub/Episode-016?id=88685
/Anime/Log-Horizon-Dub/Episode-015?id=88684
/Anime/Log-Horizon-Dub/Episode-014?id=88683
/Anime/Log-Horizon-Dub/Episode-013?id=88682
/Anime/Log-Horizon-Dub/Episode-012?id=88681
/Anime/Log-Horizon-Dub/Episode-011?id=88680
/Anime/Log-Horizon-Dub/Episode-010?id=88679
/Anime/Log-Horizon-Dub/Episode-009?id=88678
/Anime/Log-Horizon-Dub/Episode-008?id=88677
/Anime/Log-Horizon-Dub/Episode-007?id=88676
/Anime/Log-Horizon-Dub/Episode-006?id=88675
/Anime/Log-Horizon-Dub/Episode-005?id=88674
/Anime/Log-Horizon-Dub/Episode-004?id=88673
/Anime/Log-Horizon-Dub/Episode-003?id=88672
/Anime/Log-Horizon-Dub/Episode-002?id=88671
/Anime/Log-Horizon-Dub/Episode-001?id=88670
25 episodes found
Starting up downloader
('Searching for: ', 'Downloads')
Found the directory, navigating into it.
/home/jc/Downloads/Kissanime-Mass-Downloader/Downloads
/home/jc/Downloads/Kissanime-Mass-Downloader/Downloads/Log-Horizon-Dub
Found a previously downloaded episodes
I will be scanning the directory for the episodes now.
Downloaded episodes detected:[]
Traceback (most recent call last):
  File "Alpha.py", line 223, in <module>
    handler = Thread_Handler()
  File "Alpha.py", line 70, in __init__
    self.start()
  File "Alpha.py", line 75, in start
    downloader.start(dld)
  File "Alpha.py", line 85, in start
    self.findEpisodes()
  File "Alpha.py", line 125, in findEpisodes
    self.findPrev()
  File "Alpha.py", line 168, in findPrev
    self.download()
  File "Alpha.py", line 183, in download
    if str(link.text) == quality:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
jc@QVM-Ubuntu-01:~/Downloads/Kissanime-Mass-Downloader$

**Comment by jQwotos** [comment]
@xSyrix can't seem to reproduce it, so let's run through a checklist
* Python version? (currently only supports 3 and up (tested on 3.4 and 3.5))
* Try to re-clone it (not pull)
* Replace the USR and PASSWD with different credentials (their isn't an arg parse for this yet)

Tell me how it goes, i'll keep trying to look at it

**Comment by jQwotos** [comment]
@xSyrix ok just found it. It's because your running the script with Python2. Currently it only supports Python3.

**Comment by xSyrix** [comment]
@jQwotos thx, the script is running without error on python3 but is not downloading it said unable to find link for episode 

below is the output 

python3 Alpha* -l Log-Horizon-Dub
Initializing Scraper, this may take 5 - 10 seconds
Logging in with bot credentials
Logged in
Starting to Download:  https://kissanime.to/Anime/Log-Horizon-Dub
/Anime/Log-Horizon-Dub/Episode-025?id=88694
/Anime/Log-Horizon-Dub/Episode-024?id=88693
/Anime/Log-Horizon-Dub/Episode-023?id=88692
/Anime/Log-Horizon-Dub/Episode-022?id=88691
/Anime/Log-Horizon-Dub/Episode-021?id=88690
/Anime/Log-Horizon-Dub/Episode-020?id=88689
/Anime/Log-Horizon-Dub/Episode-019?id=88688
/Anime/Log-Horizon-Dub/Episode-018?id=88687
/Anime/Log-Horizon-Dub/Episode-017?id=88686
/Anime/Log-Horizon-Dub/Episode-016?id=88685
/Anime/Log-Horizon-Dub/Episode-015?id=88684
/Anime/Log-Horizon-Dub/Episode-014?id=88683
/Anime/Log-Horizon-Dub/Episode-013?id=88682
/Anime/Log-Horizon-Dub/Episode-012?id=88681
/Anime/Log-Horizon-Dub/Episode-011?id=88680
/Anime/Log-Horizon-Dub/Episode-010?id=88679
/Anime/Log-Horizon-Dub/Episode-009?id=88678
/Anime/Log-Horizon-Dub/Episode-008?id=88677
/Anime/Log-Horizon-Dub/Episode-007?id=88676
/Anime/Log-Horizon-Dub/Episode-006?id=88675
/Anime/Log-Horizon-Dub/Episode-005?id=88674
/Anime/Log-Horizon-Dub/Episode-004?id=88673
/Anime/Log-Horizon-Dub/Episode-003?id=88672
/Anime/Log-Horizon-Dub/Episode-002?id=88671
/Anime/Log-Horizon-Dub/Episode-001?id=88670
25 episodes found
Starting up downloader
Searching for:  Downloads
Found the directory, navigating into it.
/home/jc/Downloads/Kissanime-Mass-Downloader/Downloads
/home/jc/Downloads/Kissanime-Mass-Downloader/Downloads/Log-Horizon-Dub
Found a previously downloaded episodes
I will be scanning the directory for the episodes now.
Downloaded episodes detected:[]
Unable to find a link for episode: 1
Unable to find a link for episode: 2
Unable to find a link for episode: 3
Unable to find a link for episode: 4
Unable to find a link for episode: 5
Unable to find a link for episode: 6
Unable to find a link for episode: 7
Unable to find a link for episode: 8
Unable to find a link for episode: 9
Unable to find a link for episode: 10
Unable to find a link for episode: 11
Unable to find a link for episode: 12
Unable to find a link for episode: 13
Unable to find a link for episode: 14
Unable to find a link for episode: 15
Unable to find a link for episode: 16
Unable to find a link for episode: 17
Unable to find a link for episode: 18
Unable to find a link for episode: 19
Unable to find a link for episode: 20
Unable to find a link for episode: 21
Unable to find a link for episode: 22
Unable to find a link for episode: 23
Unable to find a link for episode: 24
Unable to find a link for episode: 25
Finished downloading:  https://kissanime.to/Anime/Log-Horizon-Dub

**Comment by jQwotos** [comment]
@xSyrix yea Kissanime is detecting the bot login credentials and denying entry. Change USR and PASSWD variables to a new account that's valid on Kissanime. They require an account to view direct links.

**Comment by xSyrix** [comment]
@jQwotos is working now 

thank you for spending all this time to make it work. keep up the good work
